export const ROUTES = {
    LOGIN: '/login',
    INICIO: '/inicio',
    NOTA_PARCIAL: '/NotaParcial',
    USUARIOS: '/usuarios',
    ASIGNAR_TUTORIAS: '/AsignarTutorias',
    CRONOGRAMA_ANEXOS: '/CronogramaAnexos',
    VISUALIZACION_TUTORIAS: '/VisualizacionTutorias',
    GRAFICOS_DW: '/GraficosDW',
    ESTADISTICAS_TUTORIAS: '/estadisticas-tutorias',
    REPORTE_TUTORIAS: '/ReporteTutorias',

    // Desactivadas
    FICHA_REGISTRO: '/ficha-registro',
    CONTRATOS: '/contratos',
    EVALUACION_INTEGRAL: '/evaluacion-integral',
    COMPETENCIAS: '/competencias',
    DISTRIBUIDOR: '/distribuidor',
    REGISTRAR_EVALUADOR: '/registrar-evaluador',
    HORARIOS_CLASES: '/horarios-clases',
    HORARIOS_SINCRONICOS: '/horarios-sincronicos',
    NOMINA_ESTUDIANTES: '/nomina-estudiantes',
    CORRECCION_NOTAS: '/correccion-notas',
    ATRASO_NOTAS: '/atraso-notas',
    ACTAS_NOTAS: '/actas-notas',
    ACTAS_NOTAS_FIRMA: '/actas-notas-firma',
    BIBLIOTECA: '/biblioteca',
    BIBLIOTECAS_VIRTUALES: '/bibliotecas-virtuales',
    ASISTENCIA: '/asistencia',
    PROGRAMA_ANALITICO: '/programa-analitico',
    SILABO_ASIGNATURA: '/silabo-asignatura',
    SEGUIMIENTO_SILABO: '/seguimiento-silabo',
    REPORTE_PLAN_ANALITICO: '/reporte-plan-analitico',
    CUMPLIMIENTO_SEGUIMIENTO: '/cumplimiento-seguimiento',
    MODULO_PRACTICAS: '/modulo-practicas',
    MODULO_VINCULACION: '/modulo-vinculacion'
};
